### ISSUE TITLE
Optimize edit options module

### ISSUE THREAD

**Issue by samehissam** [DJVUpp/Desktop#14]
1- Comment code using java doc.
2- What is the main problems that take much time in execution.
3- Try to solve this problems with available code.
4- If no change in performance change the available code with other that achieve your goal.

**Comment by mahmoudfouadbadwy** [comment]
Text Markup task:-

 problem statement :- 

 1- Highlight  text .
 2- Underline text.
 3- Strikeout text .
 4-Insert text .
 5- Replace text.

solution:-    by using  Graphic Class   (built in java Class)  we can draw shape after determine the 
page or an image .
The first three statement done by this steps .

![task](https://cloud.githubusercontent.com/assets/13982600/13847459/f086eed4-ec55-11e5-842d-26b2d617f689.PNG)

The last two statement we use the same steps and show note builder for writing  text .

all problems was done and the next step  saving state for reopen books.
