### ISSUE TITLE
Optimize OCR module specially with Arabic  

### ISSUE THREAD

**Issue by samehissam** [DJVUpp/Desktop#15]
1- Comment code using java doc.
2- What is the main problems that take much time in execution.
3- Try to solve this problems with available code.
4- If no change in performance change the available code with other that achieve your goal.
5-Try to solve the problem of the text font that you want to get from the image as it works good with text font more that 10.

**Comment by Mahmoud-zahran** [comment]
![p-picture of demo](https://cloud.githubusercontent.com/assets/13986219/13381237/d7ce1858-de5f-11e5-9672-4a8d00553392.PNG)
![captura](https://cloud.githubusercontent.com/assets/13986219/13383423/050b2be4-de92-11e5-8644-84c88e17a397.PNG)

**Comment by Mahmoud-zahran** [comment]
OCR Arabic :-
In the demo above, only one point-cloud template is loaded for each of the 16 gesture types. 
we can add additional templates as we wish, and even define our own custom gesture templates.

# the algorithms used in this demo ( a straightforward algorithm called $P that represents and recognizes stroke gestures as point clouds)
- now i try to recognize letter using picture to be ensure the quality of this algorithms of detecting.
- after that =>
  i will try to find how to get XML file representation using on detecting operation.
1. i will try to do algorithm convert any image to XML representation .
2. i will try to find a method to convert any font to the XML file representation.

**Comment by Mahmoud-zahran** [comment]
# steps to solution.

## when trying to recognize letter using picture to be ensure the quality of algorithm of detecting .

**hint**:- point in the algorithm consist of (x,y,stroke id) .
1. get all pixel from bitmap image using width and height .
   - [x] get the pixels using 2 loops (x of pixel width \* y of pixel height) .
2. get color of each pixel to can detect the letter shape .
   - [x] get the color of pixel using getpixel(x of pixel width ,y of pixel height) .
3. detect the letter shape from background .
   - [x]  convert image to monochrome (0,1) image to can
   - [x] get the point(x,y) of each white pixel or black .

**Comment by Mahmoud-zahran** [comment]
# steps to solution.

second step

## algorithm convert any image (the letter points) to XML representation.
1. In the $p Algorithm we have a class **GestureIO** has two method **ReadGesture()** and **WriteGesture()** .

2.write images of letters as a Gesture letter by letter.
- read all pixels of image of the letter .
- define the letter from background .
- define only the pixels represent the letter as a cloud of points .
- get(x,y) for each point or (pixel in the letter) .
- convert to XML using WriteGesture() method .

### Notes
- use number (2) to define new letters and use it to convert the input of letter to can compare with training set and detect the leter

**Comment by Mahmoud-zahran** [comment]
the white points on the letter detected as a background and detect the letter like this .
![out](https://cloud.githubusercontent.com/assets/13986219/13413402/e1a7d46a-df52-11e5-9af8-bc67da2648b2.PNG)

**Comment by Mahmoud-zahran** [comment]
# OCR problems.
- segmentation..................................(not finished exactly).
- Classification   ................................(done).

# 

## Segmentation.
- After research for lot of 2 months for How to segment Arabic word into characters
  to classify char by char for High performance.
- I **noticed** that there is no clearly method in 8 Master research and OCR books.
- So I **decided** that after asking **Dr.Ahmed sallam** to skip this phase on OCR phases and depends on powerful of classification we can only segment the word and doing classification for word 
  (Word by Word).
- We will show test for very **similar words** on classifier and its results to show **classifier power**.

**Comment by Mahmoud-zahran** [comment]
# Solution Add all small Arabic words can be segmented as (connected word) for our XML dictionary and the classifier can distinguish between words and choose the best one.

## classifier power.

![final test](https://cloud.githubusercontent.com/assets/13986219/16068412/d7924ef8-32c5-11e6-8ee7-4a45914afe4b.PNG)
![final test](https://cloud.githubusercontent.com/assets/13986219/16068413/d79e6fda-32c5-11e6-9324-e393401be38e.PNG)
