### ISSUE TITLE
Save book state and load last saved state to the user when opening that book again on any device

### ISSUE THREAD

**Issue by samehissam** [DJVUpp/Desktop#20]

**Comment by samehissam** [comment]
As I cannot assign that task to more than one so as we mention yesterday meeting, this take assigned to 
1. Mahmoud Foad.
2. Abdo Alrahman.
   3.Isslam Youssef.
   4.Youssef Ahmed.
   5.Androw Shawky.

**Comment by mahmoudfouadbadwy** [comment]
solution steps :-
1- Access djvu metadata .
2- Create dsed file that contain the metadata.
3-Dealing with dsed file and find out the appropriate method for each process .
4-Determine position of any word in the book  .
5-save new metadata to book .
6-update metadata without reopen the book .

Currently we access metadata ,create dsed file , edit it manually ,and save the meata data to book
