### ISSUE TITLE
Modules assembly

### ISSUE THREAD

**Issue by samehissam** [DJVUpp/Desktop#23]
After each member generate jar for his module with how to pdf.
The responsible for each module will have a meeting with me to add his module.

**Comment by digitamo** [comment]
# Assembling viewer-module and the core UI Process.

### What we've done:
- **Trying to reuse code from the viewer_module:**
  
   We tried to add the Frame content in the viewer module - originally meant to be for testing performance-  to the core UI and spare the time of writing new UI code, But the output came out to be not fitting nor convenient and very disturbing to see and use. In other words it would greatly degrade the user experience :worried:. 

![Image of Yaktocat](http://s32.postimg.org/btxgobmut/image.png)
- **Separate the Data and the View:**
  
   commit: `937d4c1f2377d0c627da90fbc700f489e9545b66`
   Modify the viewer_module to act like a model to store and retrieve data -book- and adapt the changes to the core UI, So the viewer_module is not a viewer any more for convenience purposes.
  
  ### output:
  
     Things worked out well, Though the overall performance is not responsive as it was in the viewer module :disappointed:. 
  ![Image of Yaktocat](http://s32.postimg.org/7o3b48a5x/image.png).
  
  ### what **TODO**  next:
  - [ ] Work on the responsiveness.
