### ISSUE TITLE
Design the modules structure.

### ISSUE THREAD

**Issue by digitamo** [DJVUpp/Desktop#4]
Define what are the modules we are going to use and what **is** in a module and what **is not** in it.

**Comment by sallamah** [comment]
شباب لو في اي حاجه قمتم بالانتهاء منها ، يا ريت تضيفوا رابط عشان اقدر اطلع عليها

يعني مثلا انا دلوقتي محتاج
رابط لـ 
Chart 
بيوضح الـ models
الي انتم بتتكلموا عليها

**Comment by digitamo** [comment]
حضرتك تقدر تشوفهم دلوقتى لو دست على الــ burndown

بس المشكله ان مفيش estimation لكل تاسك 
بس هتلاقى الــ total progress على اليمين
